name: echo-github-vars

on:
  workflow_dispatch:

jobs:
  show-vars:
    runs-on: ubuntu-latest
    steps:
      - name: Echo GitHub predefined variables
        run: |
          echo "Repository        : $GITHUB_REPOSITORY"
          echo "Branch name       : $GITHUB_REF_NAME"
          echo "Commit SHA        : $GITHUB_SHA"
          echo "Run ID            : $GITHUB_RUN_ID"
          echo "Run Number        : $GITHUB_RUN_NUMBER"
          echo "Runner OS         : $RUNNER_OS"
          echo "Workspace path    : $GITHUB_WORKSPACE"
