name: Echo on Push-uat

on:
  push:
    branches:
      - workflow_dispatch  

jobs:
  echo-job:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "ðŸš€ Code pushed successfully!"
